### ISSUE TITLE
Neue Kommentare nicht sichtbar

### ISSUE THREAD

**Issue by eifrig** [EifrigMediaGmbH/Backend_Baustellen#159]
Es werden keine neuen Kommentare mehr angezeigt. Olga bestätigt die Kommentare im Kommentar-Backend, aber sie erscheinen nicht im Baustellen-Backend.

Im Backend Admin.SCDB kommen Kommentare an, vermute daher einen Fehler im Baustellen-Backend.

Der Fehler tritt erst auf seit der letzten Änderung bzgl. alter Kommentare.

Also dieses Ticket:

EifrigMediaGmbH/Backend_Baustellen#1

**Comment by GentleSource** [comment]
@eifrig Der Fehler ist behoben. Kommentare werden jetzt wieder vom Baustellen-Backend empfangen.
